# Generated by Django 5.2.7 on 2025-10-28 11:52

import django.db.models.deletion
import truck_driver_log_book.utils.all
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('vehicle_number', models.CharField(blank=True, max_length=15)),
                ('driver_id', models.CharField(db_index=True, default=truck_driver_log_book.utils.all.generate_uuid, editable=False, unique=True)),
                ('co_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
