# Generated by Django 5.2.7 on 2025-10-28 14:34

import django.db.models.deletion
import truck_driver_log_book.utils.all
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER_BIRTH', 'Inactive'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty')], default='OFF_DUTY', max_length=25)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(db_index=True, default='53B8FA', max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(db_index=True, default='52B087', max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(db_index=True, default=truck_driver_log_book.utils.all.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='DriverDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=150, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=150, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=150, null=True)),
                ('current_cycle_used', models.DurationField(blank=True, null=True)),
                ('shipper_company', models.CharField(max_length=50)),
                ('commodity', models.CharField(max_length=50)),
                ('total_driving_miles', models.FloatField(blank=True, null=True)),
                ('truck_miles', models.FloatField(blank=True, null=True)),
                ('co_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_daily_logs', to='user_app.driver')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_daily_logs', to='user_app.driver')),
                ('events', models.ManyToManyField(blank=True, related_name='daily_logs', to='user_app.driverevent')),
                ('load_numbers', models.ManyToManyField(blank=True, related_name='driver_daily_logs', to='user_app.load')),
                ('trailer_numbers', models.ManyToManyField(blank=True, related_name='driver_daily_logs', to='user_app.trailer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
