# Generated by Django 5.2.7 on 2025-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_driverevent_load_trailer_remove_driver_driver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='id',
            field=models.CharField(db_index=True, default='D9668A', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='id',
            field=models.CharField(db_index=True, default='4CAE4E', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
