# Generated by Django 5.2.7 on 2025-10-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_load_id_alter_trailer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailylog',
            name='load_numbers',
        ),
        migrations.RemoveField(
            model_name='driverdailylog',
            name='trailer_numbers',
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.AddField(
            model_name='driverdailylog',
            name='load_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.AddField(
            model_name='driverdailylog',
            name='trailer_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
